name: second Work Flow

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "VITE_BACKEND_ORIGIN=http://api.devzoon.xyz" > .env
          echo "VITE_GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "VITE_ALLOW_HOST_NAME=cloud.devzoon.xyz" >> .env
          else
            echo "VITE_ALLOW_HOST_NAME=app.devzoon.xyz" >> .env
          fi

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine S3 path
        id: s3-path
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "path=cloud" >> $GITHUB_OUTPUT
          else
            echo "path=app" >> $GITHUB_OUTPUT
          fi

      - name: Upload to S3
        run: aws s3 sync dist/ "s3://${{ secrets.S3_BUCKET_NAME }}/${{ steps.s3-path.outputs.path }}" --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/${{ steps.s3-path.outputs.path }}/*"
